var express = require("express")
var path = require("path")
// var app = express()
var app = express.Router()
var cors = require("cors")
app.use(cors())
var bodyparser = require("body-parser")
var fileupload = require("express-fileupload")
app.use(fileupload())
var userController = require("../Controllers/userController")
app.use(bodyparser.json())
app.use(express.urlencoded({ extended: true }))
app.post("/saveSignup", userController.Signup)
app.post("/saveSignin", userController.Signin)
app.post("/saveProfile", userController.saveProfile)
app.post("/updateProfile", userController.updateProfile)
app.post("/fetchProfile", userController.fetchProfile)
app.post("/logout", userController.logout)
app.use(bodyparser.urlencoded({ extended: true }))
module.exports = app